import Navbar from "@/components/Navbar/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import { ShoppiProvider } from "@/components/context/Context";
import Provider from "@/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ShoppiProvider>
          <Provider>
            <Navbar />
            <main className="flex flex-col items-center mt-10">{children}</main>
          </Provider>
        </ShoppiProvider>
      </body>
    </html>
  );
}
